### ISSUE TITLE
cool utils. ask some use case for clear

### ISSUE THREAD

**Issue by xiaods** [facebookincubator/senpai#1]
the senpai is bin cli. if i face with k8s cluster, the node host take more pod for me. 

know can i mesure the pod correctly.

**Comment by yashbhutwala** [comment]
@xiaods I don't think you can use this utility for Kubernetes just yet, since this project uses cgroup v2 api and k8s doesn't yet support cgroup v2.

See: 
https://github.com/kubernetes/kubernetes/issues/88211
https://github.com/kubernetes/enhancements/pull/1370
https://medium.com/nttlabs/cgroup-v2-596d035be4d7

**Comment by xiaods** [comment]
@yashbhutwala got it. thanks.

**Comment by rajeeshckr** [comment]
Looks like Kubernetes has the support now for Cgroup V2. @yashbhutwala you know any pattern people use this tool in Kubernetes?
